#!/bin/bash

# now Debian-only -- 8/22/12 -- pahp


DEBUG=0 # set to 1 to DISABLE lockout and share-unmounting for testing
KEEPLOG=0 # keep or delete install log

ILOG="/var/log/labinstall.log"
touch $ILOG
chmod 666 $ILOG

echo "Starting 'install'" > $ILOG

# installer for exploits lab
export LAB="PathnameAttacks_UCLA"
#export BASE="/share/education"
export BASE="/users/sunshine/education"
export SOURCE="ExerciseCommon_UCLA"

export THISLAB="$BASE/$LAB" # lab directory
export DOWNLOADS="$BASE/$SOURCE" # repos

# support software
export INSTALL="$DOWNLOADS/scripts" 

# cd into the lab directory
pushd $THISLAB

# load the helper functions
export FUNCTIONS="$INSTALL/functions"
source $FUNCTIONS

# lock out incoming users during customization
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	NoLogin
fi

echo ">>> Beginning additional configuration of node for '$LAB' lab." >> $ILOG

echo "installing software"


####################################
# install the relevant debian packages
####################################

apt-get update
apt-get install elinks links wget curl tcpdump -y

DF_TMP=$DEBIAN_FRONTEND # save this var
export DEBIAN_FRONTEND=noninteractive # allow install without password

# set password for mysql
debconf-set-selections <<< 'mysql-server-5.1 mysql-server/root_password password verysecurepass'
debconf-set-selections <<< 'mysql-server-5.1 mysql-server/root_password_again password verysecurepass'

# install apache, php, mysql, and perl
apt-get install lamp-server^ -y &>> $ILOG
cat $THISLAB/confs/apache2.conf >> /etc/apache2/apache2.conf
a2enmod cgid

# PHP5 is automatically installed and configured.

export DEBIAN_FRONTEND=$DF_TMP # restore default

####################################
# memo.cgi installation
####################################
# Set up user accounts for Memo

echo "Setting up user accounts..."
rm -rf /home/* &>> $ILOG

# setting real passwords (see DevNotes)
useradd wilbar -p '$1$fRqkTieO$w25jISnCEBihVb/s.c.lX0' &>> $ILOG
useradd megaboz -p '$1$9hfkqg8Y$9ISt4JPDqQq.Ik6..rZXo1'
useradd barbazzo -p '$1$UKoOQUPw$vtrmLJpKLSKoV6LTlbJBD1'
useradd gustar -p '$1$YSSC3aFg$l6bRcjnZmmRAQV30Sxe.R/'

cp -r $THISLAB/memo/setup/home/* /home/ &>> $ILOG
cp -r $THISLAB/memo/setup/root/* /root/

pushd /home/
for i in *
do
	  chown $i:$i -R /home/$i
done
popd

echo "Installing memo.cgi" >> $ILOG
mkdir /usr/lib/cgi-bin
for f in memo.cgi demo.cgi
do
	cp $THISLAB/memo/$f /usr/lib/cgi-bin/
	chown root:root /usr/lib/cgi-bin/$f
	chmod go+rx /usr/lib/cgi-bin/$f
done

# make memo.cgi SUID root
chmod u+s /usr/lib/cgi-bin/memo.cgi

####################################
# root level web docs
####################################
if ! cp -ar $THISLAB/htdocs/* /var/www/html
then
	echo "Couldn't install root level docs." >> $ILOG
fi

####################################
# sundry scripts available in /root
####################################
echo "Installing submission materials..."
if ! cp -ar $THISLAB/root /
then
	echo "Couldn't install scripts in /root" >> $ILOG
else
	chmod 755 /root/*.sh
fi


echo "Success! Creating success stamp."
CreateStamp

echo ">>> Configuration complete."
YesLogin


# unmount source files
if [ $DEBUG -eq 0 ] # do this only if "for reals"
then
	$INSTALL/umountshare &
	$INSTALL/umountproj &
fi

if [ $KEEPLOG -eq 0 ]
then
	rm $ILOG
	rm /tmp/labinstall.log
fi
