#!/usr/local/bin/bash
echo

if [ $# != 2 ]
then
	echo "Usage: showcabling <experiment name> <project name>";echo
	exit
fi

for node in SWworkstation1 SWrouter ISrouter NWrouter NWworkstation1
do
	ssh -o StrictHostKeyChecking=no $node.$1.$2.isi.deterlab.net sed "s/^/$node\ /" /tmp/nicaddressing.dat 2> /dev/null

done | sort -k 2 | sed 'N;s/\n/ /' | awk '{print $1" "$3"  <- is \"wired\" to ->  "$4" "$6}'
echo
